### ISSUE TITLE
OLAP-кубы

### ISSUE THREAD

**Issue by Bykiev** [magnit-tech/magreport-open#7]
Здравствуйте, когда планируется релиз OLAP-кубов?

**Comment by v-sukhov** [comment]
Здравствуйте!
Проект переехал в другой репозиторий:
https://github.com/magnit-tech/magreport-open-2.1

И там уже есть функционал OLAP и сводных таблиц. Посмотрите, пожалуйста.

**Comment by Bykiev** [comment]
Спасибо!
